### ISSUE TITLE
Error when clearing cache

### ISSUE THREAD

**Issue by mewolari** [DashMedia/PurgeCloudFlare#1]
I've installed PurgeCloudFlare. Installation gave no errors.

When running "clear cache" an error is shown (see attachment). The setting in config.inc.php is $http_host='nmldesign.nl';

I'm working on an MacBook Pro using Chrome and Safari. When I've not enabled development mode in Cloudflare itself for the domain, MODX manager is not working in Chrome, however able to work with Safari. 

So the setting in this plugin "Clearing site cache will now activate development mode for the domain" is not working for my website.

![purgecloudflare](https://cloud.githubusercontent.com/assets/2721621/8204000/e59b127c-14e5-11e5-8816-5e1eaa551369.jpg)

**Comment by JayCarney** [comment]
Thanks for logging the error, it looks like it's trying to clear for www.nlmdesign.nl instead of nlmdesign.nl (cloudflare will have nlmdesign.nl, but not the www. version) I'll have a look into it. 

We actually run all of our sites with .htaccess redirects to the non "www" version of the url, so this is an error I'd never have found if you hadn't brought it to my attention.

**Comment by mewolari** [comment]
I'm wondering if you are able to use MODX manager without enabling the development mode in Cloudflare before logging into the MODX manager. 

When I don't do that I'm not able to fully use the manager, like editing resources.

**Comment by JayCarney** [comment]
It sounds like CF is cacheing more than you want it to, we usually set a page rule for `[url]/*.php*` to `Bypass cache` so that all the manager ajax requests to controllers don't get cached, we found this more reliable than setting a rule on `[url]/manager/*`. 

There's also a caching level setting in the cache menu that has a `No query string` option (never cache anything with a query string) but we find that the MODX manager only ever requests .php files (even if it's a script that gets returned) for the manager functionality, so the rule above covers that as well.

I would also recommend changing your `compress_js` system setting to `false` as CF will compress the output as well, we end up with setting grids etc... not loading correctly when this is set to true while running through CF.

**Comment by mewolari** [comment]
Thanks for your update.

Looks like clearing the cache is working fine now.

With the /_.php_ rule, the resources have become editable again. I assume that is the only rule you add to MODX sites?

When I go however to to “extra”-menu and visit for example MaxCDN or ContentBlocks in Firefox and Chrome they don’t show up. Safari is working fine. Do you have that same problem too?

Regards,

Joost

  https://www.linkedin.com/in/joostmeurs https://plus.google.com/+MewolariWebDevelopmentAmsterdam https://twitter.com/mewolari https://www.facebook.com/MewolariJoost Meurs
Mewolari Web Development

www.mewolari.nl http://www.mewolari.nl/ - info@mewolari.nl mailto:info@mewolari.nl
Maria Austriastraat 76, 1087 CN Amsterdam

06-21853619
KvK 52885828

Neem contact op en ervaar hoe een professionele website jouw business kan verbeteren! http://www.mewolari.nl/contact

**Comment by JayCarney** [comment]
We were having issues with some manager pages not rendering content (with dev tools open it was throwing console errors on some AJAXed javascript) especially on the system settings page, and collection pages. Setting `compress_js` to `false` fixed this for us so that CF isn't minifying/compressing  already minified and compressed js

**Comment by mewolari** [comment]
Still having problems with Chrome when Cloudflare is enabled. However Safari is working fine, even with Cloudflare enabled.

When using Bob Ray’s sitecheck it was returning errors on PurgeCloudFlare.

This was Bob’s explanation:

OK, I see the issue. That package violates the MODX convention of having the source file named for the package name.

The file is called purgecloudflare... and the package_name is CloudFlare Api Integration (it should be purgecloudflare). 

This is probably not anything to worry about unless it's crapping up the error log with spurious error messages.

I tried using the 'fix' option in SiteCheck and it did correct the package_name and eliminate the error report in SiteCheck. TBH, I'm not sure whether fixing it is a good idea or not. I was able to uninstall the package after fixing it, so it's probably OK to do so, though it would probably also be OK to just ignore the error.

  https://www.linkedin.com/in/joostmeurs https://plus.google.com/+MewolariWebDevelopmentAmsterdam https://twitter.com/mewolari https://www.facebook.com/MewolariJoost Meurs
Mewolari Web Development

www.mewolari.nl http://www.mewolari.nl/ - info@mewolari.nl mailto:info@mewolari.nl
Maria Austriastraat 76, 1087 CN Amsterdam

06-21853619
KvK 52885828

Neem contact op en ervaar hoe een professionele website jouw business kan verbeteren! http://www.mewolari.nl/contact
